name: Update Lambda deploy-to-ec2-instance

on:
  push:
    branches:
    - main
    paths:
    - lambdas/deploy-to-ec2-instance/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    # - name: Make artifact directory
    #   run: mkdir -p ./artifacts/${{ github.repository }}

    - name: Zip Folder
      run: zip -r lambda-deploy-ec2-instance.zip ./* #zip -r release.zip . -x ".git/*" ".github/*"
    
    - name: Deploy lambda code to S3 bucket
      run: aws s3 cp lambda-deploy-ec2-instance.zip s3://lambdas-python-source-code --delete
    
    - name: Update lambda
      run: aws lambda update-function-code --function-name deploy-to-ec2-instance --region us-east-1 --s3-bucket lambdas-python-source-code --s3-key lambda-deploy-ec2-instance.zip

    # - name: Make artifact directory
    #   run: mkdir -p ./artifacts/${{ github.repository }}

    # - name: Create Zip File
    #   uses: montudor/action-zip@v0.1.0
    #   with:
    #   args: zip -r ./artifacts/${{ github.repository }}/lambda-deploy-ec2-instance.zip ./src

    # - name: Push Zip to S3
    #   uses: jakejarvis/s3-sync-action@v0.3.1
    #   env:
    #   SOURCE_DIR: './artifacts/${{ github.repository }}/lambda-deploy-ec2-instance.zip'
    #   AWS_REGION: 'eu-central-1'
    #   AWS_S3_BUCKET: 'zipped-lambda-artifacts'
    #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}