name: Update Lambda deploy-to-ec2-instance

on:
  push:
    branches:
    - main
    paths:
    - lambdas/deploy-to-ec2-instance/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
    
    # - name: Move to Folder
    #   run: cd ./lambdas/deploy-to-ec2-instance 
    
    - name: Zip Folder
      run: cd ./lambdas/deploy-to-ec2-instance && zip -r lambda-deploy-ec2-instance.zip ./* 
    
    - name: Deploy lambda code to S3 bucket
      run: aws s3 cp ./lambdas/deploy-to-ec2-instance/lambda-deploy-ec2-instance.zip s3://lambdas-python-source-code
    
    - name: Update lambda
      run: aws lambda update-function-code --function-name deploy-to-ec2-instance --region us-east-1 --s3-bucket lambdas-python-source-code --s3-key lambda-deploy-ec2-instance.zip